version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: esport-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssW0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - esport-network
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Backend API
  backend:
    image: esport-match-tracker-backend
    container_name: esport-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GamingDB;User Id=sa;Password=P@ssW0rd;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - esport-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    image: esport-match-tracker-frontend
    container_name: esport-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - esport-network
    restart: unless-stopped

networks:
  esport-network:
    driver: bridge
